name: expense
version: '3.8'
networks:
  default:
    name: expense
volumes:
  mysql:
    external: true            # similar to docker volumes create mysql
  
services:
  mysql:
    image: mysql:v1.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ExpenseApp@1
      - MYSQL_USER=expense
      - MYSQL_PASSWORD=ExpenseApp@1
      - MYSQL_DATABASE=transactions
    volumes:
      - source: mysql          # -v volume-name:/path in container
        target: /var/lib/mysql
        type: volume
  backend:
    image: backend:v1.0
    container_name: backend
    command: sh -c "sleep 20 && node /opt/server/index.js"
    depends_on: 
    - mysql
  frontend:
    image: frontend:v1.0
    container_name: frontend
    depends_on:
    - backend
    ports:
      - "80:80"
